### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by Accuracy-exe** [acmpesuecc/terminal-uno#1]
The UI currently uses simple text lines to to display information.
Re-design the Interface to make it much more illustrative ( strictly in the terminal of course ).
Update "How to Play" section with new interface details
Update documentation for the game (it currently uses coded Card Ids like R6 for Red 6)
The interface must be more easier to understand and engaging for a normal player who wouldn't use coded inputs (like R6 for Red 6, etc)

An example:
- draw the cards and draw piles with ascii characters
- Animate the actions of playing a card or picking a card from draw pile

**Comment by AkshayaR11** [comment]
can i get assigned to this?

**Comment by Accuracy-exe** [comment]
!assign @AkshayaR11 90

**Comment by Keeru-2005** [comment]
please assign this to me! @Accuracy-exe

**Comment by Accuracy-exe** [comment]
!assign @Keeru-2005 90

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by Accuracy-exe** [comment]
!assign @RisuKumari11 90

**Comment by AdvaySanketi** [comment]
@Accuracy-exe assign me to this

**Comment by Accuracy-exe** [comment]
!assign @AdvaySanketi  90

**Comment by Accuracy-exe** [comment]
!assign @AdvaySanketi 90

**Comment by Accuracy-exe** [comment]
!assign @AdvaySanketi 90

**Comment by Accuracy-exe** [comment]
!assign @AdvaySanketi 90

**Comment by mahika34** [comment]
can i be assigned

**Comment by Accuracy-exe** [comment]
!assign @mahika34 90

**Comment by Accuracy-exe** [comment]
!assign @AdvaySanketi 90

**Comment by mahika34** [comment]
i am working on it

**Comment by Peeyushhhhh** [comment]
can i get assign please

**Comment by Accuracy-exe** [comment]
!assign @Peeyushhhhh 90

**Comment by Accuracy-exe** [comment]
You are already assigned a different issue @Peeyushhhhh

**Comment by SamridhiShreyaa** [comment]
can i be assigned?

**Comment by AnshulBanda** [comment]
can i get assigned this?

**Comment by stealthwhizz** [comment]
@Accuracy-exe  can you assign me this?

**Comment by Accuracy-exe** [comment]
!assign @stealthwhizz

**Comment by stealthwhizz** [comment]
> !assign @stealthwhizz

didnt get assigned
try again

**Comment by avinash-selvan** [comment]
Can I get assigned to this??
