### ISSUE TITLE
Create a settings menu to control some game rules

### ISSUE THREAD

**Issue by Accuracy-exe** [acmpesuecc/terminal-uno#3]
We all know how this game has various versions around the world.
People like setting many rules like "allow sandwiching" which basically lets a player to play all card of a specific color when applicable, etc.

Create a settings menu that lets the player to toggle some common custom rules, example: "sandwiching" (I call it that, you may call it whatever you're familiar with XD )
- Implement these custom rules in-game
- Implement at least 2 custom rules

**Comment by Ruchavw** [comment]
can you please assign this

**Comment by Accuracy-exe** [comment]
!assign @Ruchavw 90

**Comment by Accuracy-exe** [comment]
You've already been assigned to some other issue

**Comment by shreyasoni26** [comment]
please assign

**Comment by deadly-rouge** [comment]
can i try this?

**Comment by Accuracy-exe** [comment]
!assign @shreyasoni26  90

**Comment by Accuracy-exe** [comment]
!assign @deadly-rouge 90

**Comment by deadly-rouge** [comment]
can i get unassigned from it?

**Comment by deadly-rouge** [comment]
??? is it possible or i have to work on this only?

**Comment by Ruchavw** [comment]
can you please assign this?

**Comment by chandan365c** [comment]
@Accuracy-exe can you assign this to me?

**Comment by codebuddyjr** [comment]
assign me this pls

**Comment by Accuracy-exe** [comment]
!assign @chandan365c

**Comment by stealthwhizz** [comment]
@Accuracy-exe can u assign me this?

**Comment by Neonishh** [comment]
@Accuracy-exe can u assign this to me?

**Comment by jmanoj0905** [comment]
Can you assign this to me please

**Comment by chandan365c** [comment]
@Accuracy-exe I've opened a PR for this issue... Kindly review : ) 
(P.S. I apologize for taking too long)

**Comment by Neonishh** [comment]
can you assign this to me? @Accuracy-exe
