### ISSUE TITLE
Winning positions and Ranking 

### ISSUE THREAD

**Issue by Accuracy-exe** [acmpesuecc/terminal-uno#4]
Currently, the game ends when one of the players win. However, the game should continue until only we have only one active player while the winners exit the game's loop

Changes to be made:
- Game should continue after someone wins until there's only one player remaining. (the turn-based system uses a circular doubly linked list)
- Winning Position of the players must be recorded
- When game ends, rankings of all players should be displayed briefly

**Comment by avinash-selvan** [comment]
can you assign this issue to me?

**Comment by Accuracy-exe** [comment]
!assign @avinaldo22

**Comment by Krithika-Arivu** [comment]
hey could you assign this to me

**Comment by Accuracy-exe** [comment]
You've already been assigned to another issue

**Comment by ashyune** [comment]
could you assign this to me?

**Comment by Sami9692** [comment]
could u assign?

**Comment by Accuracy-exe** [comment]
Hey @Sami9692 , unfortunately this issue has already been assigned to someone else

**Comment by Accuracy-exe** [comment]
!deassign

**Comment by Accuracy-exe** [comment]
@avinaldo22 , Hi your timer is up, could you report your progress?

**Comment by ghost** [comment]
hey could you assign this to me

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by Accuracy-exe** [comment]
!assign @aakanksha-p-3

**Comment by Accuracy-exe** [comment]
!assign @RisuKumari11

**Comment by Accuracy-exe** [comment]
!assign @RisuKumari11

**Comment by bidisha1005** [comment]
can i get assigned this

**Comment by Accuracy-exe** [comment]
!assign @bidisha1005

**Comment by avinash-selvan** [comment]
> @avinaldo22 , Hi your timer is up, could you report your progress?

No luck.

**Comment by avinash-selvan** [comment]
Can I get assigned again??

**Comment by sherlockhome12** [comment]
hey can i get assigned to this??

**Comment by Accuracy-exe** [comment]
!assign @avinaldo22  50

**Comment by Accuracy-exe** [comment]
!assign @sherlockhome12 50

**Comment by AkshathaAcharya55555** [comment]
can i get assigned to this...

**Comment by Accuracy-exe** [comment]
!assign @AkshathaAcharya55555 50

**Comment by sherlockhome12** [comment]
hey i sent a pull request

**Comment by ghost** [comment]
can u come to 001

**Comment by Accuracy-exe** [comment]
@aakanksha-p-3  Hi, were u the one from a while back?

**Comment by PES2UG23CS075** [comment]
could you assign me this

**Comment by avaniajith** [comment]
could you assign this to me?

**Comment by PES2UG23CS075** [comment]
plzz assign

**Comment by Accuracy-exe** [comment]
This issue has been resolved

**Comment by Accuracy-exe** [comment]
!deassign
